# This is a config synced from rom-rb/template-gem repo
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/support/coverage.rb
    - spec/support/warnings.rb
    - spec/support/rspec_options.rb
    - Gemfile.devtools
    - "*.gemspec"

Layout/ArgumentAlignment:
  Enabled: false
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*_spec.rb"

Lint/AmbiguousBlockAssociation:
  Enabled: true
  # because 'expect { foo }.to change { bar }' is fine
  Exclude:
    - "spec/**/*.rb"

Lint/BooleanSymbol:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
  - "spec/**/*.rb"

Lint/EmptyClass:
  Exclude:
  - "spec/**/*.rb"

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - "spec/**/*.rb"

Lint/UselessMethodDefinition:
  Exclude:
    - "lib/rom/struct.rb"

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/ToEnumArguments:
  Exclude:
    - "lib/rom/command.rb"

Naming/MethodParameterName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/*-*.rb"

Naming/MethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 36

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 12

Metrics/PerceivedComplexity:
  Max: 14

Metrics/ParameterLists:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/CombinableLoops:
  Enabled: false
